expediente/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("medical.urls", namespace="medical")), 
    path("accounts/", include("django.contrib.auth.urls")),
]

medical/urls.py
from django.urls import path
from . import views

app_name = "medical"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("login/", views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout'),
    path("create-file/", views.createExp_view, name="create"),
    path('create-file/antecedentes/', views.renderiza_antecedentes_view, name='render_antecedentes'),
    path('create-file/padecimiento/', views.renderiza_padecimiento_view, name='render_padecimiento'),
    path('create-file/exploracion/', views.renderiza_exploracion_view, name='render_exploracion'),
    path('create-file/consultas/', views.renderiza_consulta_view, name='render_consultas'),
    path('help/', views.renderiza_ayuda_view, name='help'),

    # Ruta para ver el expediente
    path('view/<int:id_paciente>/', views.ver_expediente_view, name='ver_expediente'),
    path('delete/<int:id_paciente>/', views.elimina_paciente_view, name='elimina_paciente'),

    # Rutas nuevas para los formularios (create)
    path('create-file/ficha/', views.guarda_ficha_identificacion_view, name='guarda_ficha_identificacion'),
    path('create-file/antecedentes/<int:id_paciente>/', views.guarda_antecedentes_view, name='guarda_antecedentes'),
    path('create-file/padecimiento/<int:id_paciente>/', views.guarda_padecimiento_view, name='guarda_padecimiento'),
    path('create-file/exploracion/<int:id_paciente>/', views.guarda_exploracion_view, name='guarda_exploracion'),
    path('create-file/consultas/<int:id_paciente>/', views.guarda_consulta_view, name='guarda_consultas'),

    # Rutas nuevas para los formularios (update)
    path('update-file/<int:id_paciente>/ficha/', views.update_ficha_identificacion_view, name='update_ficha_identificacion'),
    path('update-file/<int:id_paciente>/antecedentes/', views.update_antecedentes_view, name='update_antecedentes'),
    path('update-file/<int:id_paciente>/padecimiento/', views.update_padecimiento_view, name='update_padecimiento'),
    path('update-file/<int:id_paciente>/exploracion/', views.update_exploracion_view, name='update_exploracion'),
    path('update-file/<int:id_paciente>/consultas/', views.update_consultas_view, name='update_consultas'),

    # Consulta desde el view
    path('add/consulta/', views.add_consulta_view, name='agregar_consulta'),
]

expediente/forms.py
from django.forms import ModelForm

templates/expedientes/add_consulta.html
{% extends "base_2.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Nuevo Expediente
      </h1>
      <p>Registra un nuevo expediente aquí.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">

    <!-- ========================================
       Formularios
    ======================================== -->
    <div id="form_consultas" class="formulario">
      <form
      id="formData_consultas"
      class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-lg"
      action=""
      method="post"
    >
        {% include "expedientes/forms/consultas.html" %}
    </form>


  </div>

</section>

<script>
  function mostrarAlerta() {
    Swal.fire({
      title: 'Guardado',
      text: 'Consulta guardada correctamente',
      icon: 'success',
      timer: 1500,
      timerProgressBar: true,
      showConfirmButton: false
    })
  }
</script>

{% endblock %}

templates/expedientes/create_antecedentes.html
{% extends "base_2.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Nuevo Expediente
      </h1>
      <p>Registra un nuevo expediente aquí.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormularios.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->
    {% if paciente %}
    <div id="form_historia_clinica">
      <form id="formData_antecedentes" class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg"
        action="{% url 'medical:guarda_antecedentes' id_paciente=paciente.id %}" method="post">
        {% include "expedientes/forms/antecedentes.html" %}
      </form>
    </div>
    {% else %}
    <div id="no_paciente" class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg text-center">
      <p>No se ha comenzado ningun registro</p>
    </div>
    {% endif %}

  </div>

</section>

<script>
  function mostrarAlerta() {
    Swal.fire({
      title: 'Guardado',
      text: 'Antecedentes guardados correctamente',
      icon: 'success',
      timer: 1500,
      timerProgressBar: true,
      showConfirmButton: false
    })
  }
</script>

{% endblock %}

templates/expedientes/create_consultas.html
{% extends "base_2.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Nuevo Expediente
      </h1>
      <p>Registra un nuevo expediente aquí.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormularios.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->

    {% if paciente %}
    <div id="form_consultas" class="formulario">
      <form
      id="formData_consultas"
      class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg"
      action="{% url 'medical:guarda_consultas' id_paciente=paciente.id %}"
      method="post"
    >
        {% include "expedientes/forms/consultas.html" %}
    </form>
    {% else %}
    <div id="no_paciente" class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg text-center">
      <p>No se ha comenzado ningun registro</p>
    </div>
    {% endif %}
      </div>

  </div>

</section>

<script>
  function mostrarAlerta() {
    Swal.fire({
      title: 'Guardado',
      text: 'Consulta guardada correctamente',
      icon: 'success',
      timer: 1500,
      timerProgressBar: true,
      showConfirmButton: false
    })
  }
</script>

{% endblock %}

templates/expedientes/create_exploracion.html
{% extends "base_2.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Nuevo Expediente
      </h1>
      <p>Registra un nuevo expediente aquí.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormularios.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->

    {% if paciente %}
    <div id="form_exploracion_fisica" class="formulario">
      <form
      id="formData_exploracion_fisica"
      class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg"
      action="{% url 'medical:guarda_exploracion' id_paciente=paciente.id %}"
      method="post"
    >
        {% include "expedientes/forms/exploracion_fisica.html" %}
    </form>
    {% else %}
    <div id="no_paciente" class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg text-center">
      <p>No se ha comenzado ningun registro</p>
    </div>
    {% endif %}
      </div>

  </div>

</section>

<script>
  function mostrarAlerta() {
    Swal.fire({
      title: 'Guardado',
      text: 'Exploracion física guardada correctamente',
      icon: 'success',
      timer: 1500,
      timerProgressBar: true,
      showConfirmButton: false
    })
  }


  function calcularIMC() {
    // Obtener los valores de altura y peso
    var alturaInput = document.getElementById('talla').value;
    var pesoInput = document.getElementById('peso').value;
  
    // Eliminar cualquier carácter no numérico excepto el punto decimal
    var altura = parseFloat(alturaInput.replace(/[^0-9.]/g, ''));
    var peso = parseFloat(pesoInput.replace(/[^0-9.]/g, ''));
  
    // Verificar si los valores son válidos
    if (isNaN(altura) || isNaN(peso) || altura <= 0 || peso <= 0) {
      // Si uno o ambos campos están vacíos o no son válidos, salir de la función
      return;
    }
  
    // Calcular el IMC
    var imc = peso / Math.pow(altura / 100, 2);
  
    // Redondear el resultado a dos decimales
    imc = imc.toFixed(1);
  
    // Colocar el resultado en el campo IMC
    document.getElementById('imc').value = imc;
  }
  
  // Llamar a la función calcularIMC cuando se cambie el valor de los campos de altura y peso
  document.getElementById('talla').addEventListener('input', calcularIMC);
  document.getElementById('peso').addEventListener('input', calcularIMC);
  
</script>

{% endblock %}

templates/expedientes/create_ficha.html
{% extends "base_2.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Nuevo Expediente
      </h1>
      <p>Registra un nuevo expediente aquí.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormularios.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->

    <div id="form_ficha_identificacion">
      <form id="form_ficha_identificacion" class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg"
        action="{% url 'medical:guarda_ficha_identificacion'%}" method="post">
        {% include "expedientes/forms/ficha_identificacion.html" %}
      </form>
    </div>

  </div>

</section>

<script>
  function calcularEdad() {
    let fechaNacimiento = new Date(document.getElementById("fecha_nacimiento").value);
    let ahora = new Date();

    let edad = ahora.getFullYear() - fechaNacimiento.getFullYear();
    let meses = ahora.getMonth() - fechaNacimiento.getMonth();

    // Verificar si aún no ha cumplido años
    if (ahora.getMonth() < fechaNacimiento.getMonth() ||
      (ahora.getMonth() == fechaNacimiento.getMonth() && ahora.getDate() < fechaNacimiento.getDate())) {
      edad--;
      meses += 12;
    }

    document.getElementById("edad").value = edad + " años y " + meses + " meses";
  }


  function mostrarAlerta() {
    Swal.fire({
      title: 'Guardado',
      text: 'Paciente creado correctamente',
      icon: 'success',
      timer: 1500,
      timerProgressBar: true,
      showConfirmButton: false
    })
  }
</script>

{% endblock %}

templates/expedientes/create_padecimiento.html
{% extends "base_2.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Nuevo Expediente
      </h1>
      <p>Registra un nuevo expediente aquí.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormularios.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->
    {% if paciente %}
    <form id="formData_padecimiento_actual" class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg"
      action="{% url 'medical:guarda_padecimiento' id_paciente=paciente.id %}" method="post">
      <div id="form_padecimiento_actual" class="formulario">
        {% include "expedientes/forms/padecimiento_actual.html" %}
      </div>
    </form>
    {% else %}
    <div id="no_paciente" class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg text-center">
      <p>No se ha comenzado ningun registro</p>
    </div>
    {% endif %}
  </div>

</section>

<script>
  function mostrarAlerta() {
    Swal.fire({
      title: 'Guardado',
      text: 'Padecimiento actual guardado correctamente',
      icon: 'success',
      timer: 1500,
      timerProgressBar: true,
      showConfirmButton: false
    })
  }
</script>

{% endblock %}

templates/expedientes/create_padecimientos.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Nuevo Expediente
      </h1>
      <p>Registra un nuevo expediente aquí.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormularios.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->

    <div id="form_padecimiento_actual" class="formulario">
        {% include "expedientes/forms/padecimiento_actual.html" %}
      </div>

  </div>

</section>

{% endblock %}

templates/expedientes/update_antecedentes.html
{% extends "base_2.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Editar Expediente
      </h1>
      <p>Modifica los campos necesarios a continuacion.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormulariosUpdate.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->

    <div id="form_historia_clinica">
      <form id="formData_antecedentes" class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg"
        action="{% url 'medical:update_antecedentes' paciente.id %}" method="post">
        {% include "expedientes/forms/antecedentes.html" %}
      </form>
    </div>

  </div>

</section>

<script>
  function mostrarAlerta() {
    Swal.fire({
      title: 'Guardado',
      text: 'Paciente actualizado correctamente',
      icon: 'success',
      timer: 1500,
      timerProgressBar: true,
      showConfirmButton: false
    })
  }
</script>

{% endblock %}

templates/expedientes/update_consultas.html
{% extends "base_2.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Editar Expediente
      </h1>
      <p>Modifica los campos necesarios a continuacion.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormulariosUpdate.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->

    <div id="form_consultas" class="formulario">
      <form
      id="formData_consultas"
      class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg"
      action="{% url 'medical:update_consultas' paciente.id %}"
      method="post"
    >
        {% include "expedientes/forms/consultas.html" %}
    </form>
  </div>

</section>

<script>
  function mostrarAlerta() {
    Swal.fire({
      title: 'Guardado',
      text: 'Paciente actualizado correctamente',
      icon: 'success',
      timer: 1500,
      timerProgressBar: true,
      showConfirmButton: false
    })
  }
</script>

{% endblock %}

templates/expedientes/update_exploracion.html
{% extends "base_2.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Editar Expediente
      </h1>
      <p>Modifica los campos necesarios a continuacion.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormulariosUpdate.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->

    <div id="form_exploracion_fisica" class="formulario">
      <form
      id="formData_exploracion_fisica"
      class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg"
      action="{% url 'medical:update_exploracion' paciente.id %}"
      method="post"
    >
        {% include "expedientes/forms/exploracion_fisica.html" %}
    </form>
  </div>

</section>

<script>
  function mostrarAlerta() {
    Swal.fire({
      title: 'Guardado',
      text: 'Paciente actualizado correctamente',
      icon: 'success',
      timer: 1500,
      timerProgressBar: true,
      showConfirmButton: false
    })
  }


  function calcularIMC() {
    // Obtener los valores de altura y peso
    var alturaInput = document.getElementById('talla').value;
    var pesoInput = document.getElementById('peso').value;
  
    // Eliminar cualquier carácter no numérico excepto el punto decimal
    var altura = parseFloat(alturaInput.replace(/[^0-9.]/g, ''));
    var peso = parseFloat(pesoInput.replace(/[^0-9.]/g, ''));
  
    // Verificar si los valores son válidos
    if (isNaN(altura) || isNaN(peso) || altura <= 0 || peso <= 0) {
      // Si uno o ambos campos están vacíos o no son válidos, salir de la función
      return;
    }
  
    // Calcular el IMC
    var imc = peso / Math.pow(altura / 100, 2);
  
    // Redondear el resultado a dos decimales
    imc = imc.toFixed(1);
  
    // Colocar el resultado en el campo IMC
    document.getElementById('imc').value = imc;
  }
  
  // Llamar a la función calcularIMC cuando se cambie el valor de los campos de altura y peso
  document.getElementById('talla').addEventListener('input', calcularIMC);
  document.getElementById('peso').addEventListener('input', calcularIMC);
  
  
</script>

{% endblock %}

templates/expedientes/update_ficha.html
{% extends "base_2.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Editar Expediente
      </h1>
      <p>Modifica los campos necesarios a continuacion.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormulariosUpdate.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->

    <div id="form_ficha_identificacion">
      <form id="form_ficha_identificacion" class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg" action="{% url 'medical:update_ficha_identificacion' paciente.id %}" method="post">
      {% include "expedientes/forms/ficha_identificacion.html" %}
      </form>
    </div>

  </div>

</section>

<script>
  function calcularEdad() {
    var fechaNacimiento = document.getElementById("fecha_nacimiento").value;
    var fechaActual = new Date();
    var nacimiento = new Date(fechaNacimiento);
    var edad = fechaActual.getFullYear() - nacimiento.getFullYear();
    var meses = fechaActual.getMonth() - nacimiento.getMonth();
  
    if (meses < 0 || (meses === 0 && fechaActual.getDate() < nacimiento.getDate())) {
      edad--;
      meses += 12;
    }
  
    var edadCompleta = edad + " años y " + meses + " meses";
    document.getElementById("edad").value = edadCompleta;
  }
  
  window.onload = function() {
    calcularEdad();
  };

    function mostrarAlerta() {
      Swal.fire({
        title: 'Guardado',
        text: 'Paciente actualizado correctamente',
        icon: 'success',
        timer: 1500,
        timerProgressBar: true,
        showConfirmButton: false
      })
    }

</script>

{% endblock %}

templates/expedientes/update_padecimiento.html
{% extends "base_2.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Editar Expediente
      </h1>
      <p>Modifica los campos necesarios a continuacion.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormulariosUpdate.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->
    <form id="formData_padecimiento_actual" class="lg:container lg:mx-auto bg-background p-10 space-y-8 rounded-b-lg"
      action="{% url 'medical:update_padecimiento' paciente.id %}" method="post">
      <div id="form_padecimiento_actual" class="formulario">
        {% include "expedientes/forms/padecimiento_actual.html" %}
      </div>
    </form>
  </div>

</section>

<script>
  function mostrarAlerta() {
    Swal.fire({
      title: 'Guardado',
      text: 'Paciente actualizado correctamente',
      icon: 'success',
      timer: 1500,
      timerProgressBar: true,
      showConfirmButton: false
    })
  }
</script>

{% endblock %}

templates/expedientes/update_padecimientos.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="lg:px-0 min-h-screen">
  <!-- ========================================
    AQUI VA EL NAVBAR
 ======================================== -->
  {% include "plantillas/navbar.html" %}

  <!-- Header -->
  <div class="py-10 border-b-2 border-gray-200 bg-white md:px-6">
    <div class="lg:container lg:mx-auto">
      <h1 class="uppercase font-semibold text-main text-xl">
        Nuevo Expediente
      </h1>
      <p>Registra un nuevo expediente aquí.</p>
    </div>
  </div>

  <div class="py-10 bg-white md:px-6">
    <!-- ========================================
       Barra de navegacion para los formularios
    ======================================== -->
    {% include "plantillas/navbarFormulariosUpdate.html" %}

    <!-- ========================================
       Formularios
    ======================================== -->

    <div id="form_padecimiento_actual" class="formulario">
        {% include "expedientes/forms/padecimiento_actual.html" %}
      </div>

  </div>

</section>

{% endblock %}